services:
  database:
    container_name: "jogonlog_database"
    build:
      context: "./database"
      dockerfile: "Dockerfile"
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - "./database/postgres.env"
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - jogonlog_web_proxy

  backend:
    container_name: "jogonlog_backend"
    image: "jogonlog_backend:dev"
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/usr/src/backend
    networks:
      - jogonlog_web_proxy

  frontend:
    container_name: "jogonlog_frontend"
    image: "jogonlog_frontend:dev"
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
      - frontend_node_modules:/usr/src/frontend/node_modules
    networks:
      - jogonlog_web_proxy

  proxy:
    container_name: "jogonlog_proxy"
    image: "jogonlog_proxy:dev"
    build:
      context: "./web_proxy"
      dockerfile: "Dockerfile"
    ports:
      - '8080:80'
    networks:
      - jogonlog_web_proxy
    depends_on:
      - backend
      - frontend

networks:
  jogonlog_web_proxy:
    driver: bridge

volumes:
  database_volume:
  frontend_node_modules:
